### ISSUE TITLE
Unsubscribing from observables

### ISSUE THREAD

**Issue by Enngage** [Kentico/cloud-sample-app-vue#1]
Hey,

When you are loading data like:

```javascript
let fetchProductStatuses = () => {
    Client.taxonomy("product_status")
        .get()
        .subscribe(response => {
            productStatuses = response.taxonomy.terms;
            notifyChange();
        });
}
```
You should also have a way of unsubscribing from the Observable when its no longer needed (usually when user goes to another page, but can be different). The consequences  of not doing so can be quite important because the subscription code upon completion can be executed **after** user left the page. Ideally, you should **cancel** the HTTP request (as well as the execution of code in your subscribe section) when user leaves the page or you no longer need it. 

In Angular, this can be best achieved with **`takeUntil`** that uses a notifier on **ngDestroy** which gets called when component gets destroyed. In React, you could use `onUnmount`. Not sure about Vue, but surely there is something similar.

➡️ `beforeDestroyed`

To see that your code is cancelling request properly, add a `delay` to your Observables and try switching pages. You should see that upon switching to another page, the request is cancelled in **network** tab in dev tools of your browser. See the top answer [here ](https://stackoverflow.com/questions/38008334/angular-rxjs-when-should-i-unsubscribe-from-subscription) to see how it can be used with Angular.

Similar PR in the React sample app (for inspiration): https://github.com/Kentico/cloud-sample-app-react/issues/66

**Comment by sripaulgit** [comment]
@Enngage can I implement unsubscribe during `beforeDestroy()` or `destroyed()` method. I am a little confused because during `beforeDestroy()` the component is still fully functional. Not sure what's the right place. But I think its safer to do it in `destroyed()`. Let me know your thoughts.

**Comment by petrsvihlik** [comment]
@Enngage is on vacation until tomorrow. he'll answer then. 
@Simply007 do you know the answer, by any chance?

**Comment by Enngage** [comment]
@sripaulgit I'm way more familiar with Angular then React, but `destroyed()` seems like a way to go. You shouldn't cancel observables while the page is still active so either use destroyed or some 'afterDestroy' if there is any. 

Also, I would highly recommend using `takeUntil` rxjs operator rather then using the `unsubscribe` method on the obsevables. This is because using takeUntil uses less code and is easier to manage.

**Comment by sripaulgit** [comment]
Thanks @Enngage. I'd be interested to take this on and implement with `takeUtil`. I just filed a PR for similar one in the react sample.

**Comment by Simply007** [comment]
In my opinion, it is better to use beforeDestroyed. This is how it is solved in vue-rx.
I have just created poll on twitter - let's see :-)

https://twitter.com/ChrastinaOndrej/status/1007574909558632449

**Comment by Simply007** [comment]
Linking issue: https://github.com/Kentico/cloud-sample-app-react/issues/66
* implementation would be similar
