### ISSUE TITLE
Extract API keys definition to .env

### ISSUE THREAD

**Issue by Simply007** [Kentico/cloud-sample-app-vue#23]
### Motivation

According to https://github.com/Kentico/cloud-sample-app-vue/pull/19#issuecomment-439697464 - it is easily possible to commit API keys as a part of the pull request in `Client.js` file. 

Currently, it is possible to configure the project :
* [by using the configuration page](https://github.com/Kentico/cloud-sample-app-vue#connecting-to-your-sample-project)
* [configure the client manually](https://github.com/Kentico/cloud-sample-app-vue#connecting-to-your-project-manually)

When you configure your project manually it is required to temporarilly change the source code in `Client.js` file and that could leads to commit this unintended change that was used for, let's say testing purposes.

If the project ID was loaded from environment, as an environment variable, it would eliminate possibility for unintended commit to Client.js.
Loading environment variables is possible utins [dotenv](https://www.npmjs.com/package/dotenv) library.

### Proposed solution

Best practice nowadays is to use environment variables stored in .env file.

* Set up .gitignore to ignore .env file
* Configure `Client.js` to use .env definition for keys (projectId and previewApiKey)
* Update Readme

### Additional context

* Highly used is dotenv librady: https://www.npmjs.com/package/dotenv

**Comment by BachAmadou** [comment]
@simply007, thanks you. Will keep you up to date
