### ISSUE TITLE
Define common code format

### ISSUE THREAD

**Issue by Simply007** [Kentico/cloud-sample-app-vue#6]
It would be great to have a common format specification for the components.

At least have all the vue components with same format:
* I recommend 2 spaces for javascript code and 4 for html part
* set up [.eslintrc.json](https://eslint.org/docs/user-guide/configuring)

**Comment by cbeard87** [comment]
Hey! I'd be down to work on this. 

My employer is looking into moving some of our Kentico CMS projects over to Kentico Cloud and Vue, so we've been setting up similar configs internally.

**Comment by Simply007** [comment]
Hello @cbeard87,

that would be great! Do you need any guidance?

If you accept the collaborator invite I've just sent you, we'll be able to assign the issue directly to you.

**Comment by cbeard87** [comment]
@Simply007 For right now I can just go ahead and pull the ESLint config out of the package.json and
into its own file.

Aside from the tab sizing options, are there any other conventions we'd like to standardize around?

**Comment by Simply007** [comment]
I would recommend going through the configuration used by official CLI: 
* https://github.com/vuejs/vue-cli
* https://cli.vuejs.org/config/#eslint

In my opinion, it is the best choice to follow their recommendations and default set up.
