### ISSUE TITLE
add record to Up For Grabs

### ISSUE THREAD

**Issue by Simply007** [Kentico/cloud-sample-app-vue#7]
It would be good to create a pull request for Up For Grabs site.
https://github.com/up-for-grabs/up-for-grabs.net

As we did with other repos:
* https://github.com/up-for-grabs/up-for-grabs.net/pull/826

**Comment by ritwik12** [comment]
@Simply007 Nice, you created an issue for this :sweat_smile:

**Comment by Simply007** [comment]
@ritwik12 - yeap, I like it organized :satisfied: Thanks for merge.

**Comment by ritwik12** [comment]
@Simply007 Your welcome
