### ISSUE TITLE
Upgrade to KC SDK v4

### ISSUE THREAD

**Issue by Simply007** [Kentico/cloud-sample-app-vue#8]
Upgrade to new version of Kentico cloud delivery SDK v4 - currently installed one is deprecated.

New link:
https://www.npmjs.com/package/kentico-cloud-delivery

As we have done with react sample app:
https://github.com/Kentico/cloud-sample-app-react/pull/79

**Comment by sripaulgit** [comment]
@Simply007 I can upgrade the SDK to v4.
